// Re-export from new location for backward compatibility
export {
  type Config,
  type CredentialSource,
  clearConfig,
  clearConfigFile,
  clearKeychain,
  getCredentials,
  getCredentialsFromEnv,
  getCredentialsFromFile,
  getKeychainCredentials,
  hasCredentials,
  hasCredentialsSync,
  hasKeychainSupport,
  loadConfig,
  promptLogin,
  requireCredentials,
  saveConfig,
  saveToKeychain,
} from "./shared/config.js";
